# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\13595\PycharmProjects\music-player\main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1023, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1023, 670))
        font = QtGui.QFont()
        font.setFamily("宋体")
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(0, 50))
        self.header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(15, 0, 17, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_icon = QtWidgets.QPushButton(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_icon.sizePolicy().hasHeightForWidth())
        self.btn_icon.setSizePolicy(sizePolicy)
        self.btn_icon.setMinimumSize(QtCore.QSize(22, 22))
        self.btn_icon.setMaximumSize(QtCore.QSize(22, 22))
        self.btn_icon.setText("")
        self.btn_icon.setObjectName("btn_icon")
        self.horizontalLayout.addWidget(self.btn_icon)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.le_search = QtWidgets.QLineEdit(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_search.sizePolicy().hasHeightForWidth())
        self.le_search.setSizePolicy(sizePolicy)
        self.le_search.setMinimumSize(QtCore.QSize(218, 22))
        self.le_search.setMaximumSize(QtCore.QSize(218, 22))
        self.le_search.setObjectName("le_search")
        self.horizontalLayout.addWidget(self.le_search)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_set = QtWidgets.QPushButton(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_set.sizePolicy().hasHeightForWidth())
        self.btn_set.setSizePolicy(sizePolicy)
        self.btn_set.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_set.setMaximumSize(QtCore.QSize(15, 15))
        self.btn_set.setText("")
        self.btn_set.setObjectName("btn_set")
        self.horizontalLayout.addWidget(self.btn_set)
        self.btn_window_min = QtWidgets.QPushButton(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_window_min.sizePolicy().hasHeightForWidth())
        self.btn_window_min.setSizePolicy(sizePolicy)
        self.btn_window_min.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_window_min.setMaximumSize(QtCore.QSize(15, 15))
        self.btn_window_min.setText("")
        self.btn_window_min.setObjectName("btn_window_min")
        self.horizontalLayout.addWidget(self.btn_window_min)
        self.btn_window_max = QtWidgets.QPushButton(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_window_max.sizePolicy().hasHeightForWidth())
        self.btn_window_max.setSizePolicy(sizePolicy)
        self.btn_window_max.setMinimumSize(QtCore.QSize(13, 13))
        self.btn_window_max.setMaximumSize(QtCore.QSize(13, 13))
        self.btn_window_max.setText("")
        self.btn_window_max.setObjectName("btn_window_max")
        self.horizontalLayout.addWidget(self.btn_window_max)
        self.btn_window_close = QtWidgets.QPushButton(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_window_close.sizePolicy().hasHeightForWidth())
        self.btn_window_close.setSizePolicy(sizePolicy)
        self.btn_window_close.setMinimumSize(QtCore.QSize(15, 15))
        self.btn_window_close.setMaximumSize(QtCore.QSize(15, 15))
        self.btn_window_close.setText("")
        self.btn_window_close.setObjectName("btn_window_close")
        self.horizontalLayout.addWidget(self.btn_window_close)
        self.verticalLayout.addWidget(self.header)
        self.main_stacked_widget = QtWidgets.QStackedWidget(Form)
        self.main_stacked_widget.setObjectName("main_stacked_widget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_page)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.navigation = QtWidgets.QListWidget(self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigation.sizePolicy().hasHeightForWidth())
        self.navigation.setSizePolicy(sizePolicy)
        self.navigation.setMinimumSize(QtCore.QSize(191, 0))
        self.navigation.setMaximumSize(QtCore.QSize(191, 16777215))
        self.navigation.setAutoScrollMargin(16)
        self.navigation.setViewMode(QtWidgets.QListView.ListMode)
        self.navigation.setObjectName("navigation")
        self.gridLayout_4.addWidget(self.navigation, 0, 0, 1, 1)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.main_page)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.music_list_detail = QtWidgets.QWidget()
        self.music_list_detail.setObjectName("music_list_detail")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.music_list_detail)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.music_list_detail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 308))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 308))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setContentsMargins(30, 20, 30, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setHorizontalSpacing(20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.music_count = QtWidgets.QLabel(self.widget_2)
        self.music_count.setObjectName("music_count")
        self.gridLayout_5.addWidget(self.music_count, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 148, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 2, 2, 1, 1)
        self.music_list_image = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_list_image.sizePolicy().hasHeightForWidth())
        self.music_list_image.setSizePolicy(sizePolicy)
        self.music_list_image.setMinimumSize(QtCore.QSize(198, 198))
        self.music_list_image.setObjectName("music_list_image")
        self.gridLayout_5.addWidget(self.music_list_image, 0, 0, 3, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 2, 6, 1, 1)
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(225, 225, 226, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(225, 225, 226);")
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 2, 4, 1, 1)
        self.music_list_play_count = QtWidgets.QLabel(self.widget_2)
        self.music_list_play_count.setObjectName("music_list_play_count")
        self.gridLayout_5.addWidget(self.music_list_play_count, 0, 6, 1, 1)
        self.music_list_name = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.music_list_name.setFont(font)
        self.music_list_name.setObjectName("music_list_name")
        self.gridLayout_5.addWidget(self.music_list_name, 0, 2, 1, 1)
        self.music_list_date = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.music_list_date.setFont(font)
        self.music_list_date.setObjectName("music_list_date")
        self.gridLayout_5.addWidget(self.music_list_date, 1, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(82, 31))
        self.label_4.setMaximumSize(QtCore.QSize(82, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(503, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 2, 1, 1, 1)
        self.music_list_search = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_list_search.sizePolicy().hasHeightForWidth())
        self.music_list_search.setSizePolicy(sizePolicy)
        self.music_list_search.setMinimumSize(QtCore.QSize(172, 0))
        self.music_list_search.setMaximumSize(QtCore.QSize(172, 16777215))
        self.music_list_search.setObjectName("music_list_search")
        self.gridLayout_6.addWidget(self.music_list_search, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)
        self.musics = QtWidgets.QTableWidget(self.music_list_detail)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.musics.sizePolicy().hasHeightForWidth())
        self.musics.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.musics.setFont(font)
        self.musics.setStyleSheet("border-bottom-color: rgb(225, 225, 225);")
        self.musics.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.musics.setObjectName("musics")
        self.musics.setColumnCount(0)
        self.musics.setRowCount(0)
        self.gridLayout_3.addWidget(self.musics, 1, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.music_list_detail)
        self.local_music_page = QtWidgets.QWidget()
        self.local_music_page.setObjectName("local_music_page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.local_music_page)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget = QtWidgets.QWidget(self.local_music_page)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 30, 0, 20)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.btn_choose_dir = QtWidgets.QPushButton(self.widget)
        self.btn_choose_dir.setObjectName("btn_choose_dir")
        self.horizontalLayout_3.addWidget(self.btn_choose_dir)
        spacerItem10 = QtWidgets.QSpacerItem(430, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.le_search_local_music = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_search_local_music.sizePolicy().hasHeightForWidth())
        self.le_search_local_music.setSizePolicy(sizePolicy)
        self.le_search_local_music.setMinimumSize(QtCore.QSize(172, 0))
        self.le_search_local_music.setMaximumSize(QtCore.QSize(172, 16777215))
        self.le_search_local_music.setObjectName("le_search_local_music")
        self.horizontalLayout_3.addWidget(self.le_search_local_music)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.gridLayout_8.addWidget(self.widget, 0, 0, 1, 1)
        self.tb_local_music = QtWidgets.QTableWidget(self.local_music_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tb_local_music.setFont(font)
        self.tb_local_music.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_local_music.setObjectName("tb_local_music")
        self.tb_local_music.setColumnCount(0)
        self.tb_local_music.setRowCount(0)
        self.gridLayout_8.addWidget(self.tb_local_music, 1, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.local_music_page)
        self.gridLayout_4.addWidget(self.stackedWidget_2, 0, 1, 2, 1)
        self.music_info_widget = QtWidgets.QWidget(self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_info_widget.sizePolicy().hasHeightForWidth())
        self.music_info_widget.setSizePolicy(sizePolicy)
        self.music_info_widget.setMinimumSize(QtCore.QSize(191, 56))
        self.music_info_widget.setMaximumSize(QtCore.QSize(191, 56))
        self.music_info_widget.setObjectName("music_info_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.music_info_widget)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_music_image = QtWidgets.QPushButton(self.music_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_music_image.sizePolicy().hasHeightForWidth())
        self.btn_music_image.setSizePolicy(sizePolicy)
        self.btn_music_image.setMinimumSize(QtCore.QSize(44, 44))
        self.btn_music_image.setMaximumSize(QtCore.QSize(44, 44))
        self.btn_music_image.setText("")
        self.btn_music_image.setObjectName("btn_music_image")
        self.gridLayout_2.addWidget(self.btn_music_image, 0, 0, 2, 1)
        self.label_music_title = QtWidgets.QLabel(self.music_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_music_title.sizePolicy().hasHeightForWidth())
        self.label_music_title.setSizePolicy(sizePolicy)
        self.label_music_title.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_music_title.setText("")
        self.label_music_title.setObjectName("label_music_title")
        self.gridLayout_2.addWidget(self.label_music_title, 0, 1, 1, 1)
        self.label_music_artist = QtWidgets.QLabel(self.music_info_widget)
        self.label_music_artist.setText("")
        self.label_music_artist.setObjectName("label_music_artist")
        self.gridLayout_2.addWidget(self.label_music_artist, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.music_info_widget, 1, 0, 1, 1)
        self.main_stacked_widget.addWidget(self.main_page)
        self.play_page = QtWidgets.QWidget()
        self.play_page.setObjectName("play_page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.play_page)
        self.gridLayout_7.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setVerticalSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_title = QtWidgets.QLabel(self.play_page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout_7.addWidget(self.label_title, 0, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(431, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem12, 0, 0, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(516, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 0, 3, 1, 5)
        spacerItem14 = QtWidgets.QSpacerItem(381, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem14, 1, 0, 1, 1)
        self.label_artist = QtWidgets.QLabel(self.play_page)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_artist.setFont(font)
        self.label_artist.setObjectName("label_artist")
        self.gridLayout_7.addWidget(self.label_artist, 1, 3, 1, 1)
        self.btn_return = QtWidgets.QPushButton(self.play_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_return.sizePolicy().hasHeightForWidth())
        self.btn_return.setSizePolicy(sizePolicy)
        self.btn_return.setMinimumSize(QtCore.QSize(36, 26))
        self.btn_return.setMaximumSize(QtCore.QSize(36, 26))
        self.btn_return.setText("")
        self.btn_return.setObjectName("btn_return")
        self.gridLayout_7.addWidget(self.btn_return, 1, 5, 1, 1)
        self.label_album = QtWidgets.QLabel(self.play_page)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_album.setFont(font)
        self.label_album.setObjectName("label_album")
        self.gridLayout_7.addWidget(self.label_album, 1, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.play_page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 39))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 20, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_lyric = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(13)
        self.label_lyric.setFont(font)
        self.label_lyric.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label_lyric.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_lyric.setText("")
        self.label_lyric.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lyric.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_lyric.setObjectName("label_lyric")
        self.gridLayout.addWidget(self.label_lyric, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 2, 0, 1, 8)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem15, 1, 4, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem16, 1, 6, 1, 1)
        self.main_stacked_widget.addWidget(self.play_page)
        self.verticalLayout.addWidget(self.main_stacked_widget)
        self.footer = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footer.sizePolicy().hasHeightForWidth())
        self.footer.setSizePolicy(sizePolicy)
        self.footer.setMinimumSize(QtCore.QSize(0, 48))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 48))
        self.footer.setObjectName("footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_2.setContentsMargins(22, 0, 6, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_previous = QtWidgets.QPushButton(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_previous.sizePolicy().hasHeightForWidth())
        self.btn_previous.setSizePolicy(sizePolicy)
        self.btn_previous.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_previous.setText("")
        self.btn_previous.setObjectName("btn_previous")
        self.horizontalLayout_2.addWidget(self.btn_previous)
        spacerItem17 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.btn_start = QtWidgets.QPushButton(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(38, 38))
        self.btn_start.setText("")
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_2.addWidget(self.btn_start)
        spacerItem18 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem18)
        self.btn_next = QtWidgets.QPushButton(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        self.btn_next.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_next.setText("")
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_2.addWidget(self.btn_next)
        spacerItem19 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.label_pos = QtWidgets.QLabel(self.footer)
        self.label_pos.setObjectName("label_pos")
        self.horizontalLayout_2.addWidget(self.label_pos)
        spacerItem20 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem20)
        self.slider_progress = QtWidgets.QSlider(self.footer)
        self.slider_progress.setOrientation(QtCore.Qt.Horizontal)
        self.slider_progress.setObjectName("slider_progress")
        self.horizontalLayout_2.addWidget(self.slider_progress)
        spacerItem21 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem21)
        self.label_duration = QtWidgets.QLabel(self.footer)
        self.label_duration.setObjectName("label_duration")
        self.horizontalLayout_2.addWidget(self.label_duration)
        spacerItem22 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem22)
        self.btn_mute = QtWidgets.QPushButton(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mute.sizePolicy().hasHeightForWidth())
        self.btn_mute.setSizePolicy(sizePolicy)
        self.btn_mute.setMinimumSize(QtCore.QSize(18, 18))
        self.btn_mute.setMaximumSize(QtCore.QSize(18, 18))
        self.btn_mute.setText("")
        self.btn_mute.setObjectName("btn_mute")
        self.horizontalLayout_2.addWidget(self.btn_mute)
        spacerItem23 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.slider_volume = QtWidgets.QSlider(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_volume.sizePolicy().hasHeightForWidth())
        self.slider_volume.setSizePolicy(sizePolicy)
        self.slider_volume.setMaximum(100)
        self.slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_volume.setObjectName("slider_volume")
        self.horizontalLayout_2.addWidget(self.slider_volume)
        spacerItem24 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem24)
        self.btn_play_mode = QtWidgets.QPushButton(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play_mode.sizePolicy().hasHeightForWidth())
        self.btn_play_mode.setSizePolicy(sizePolicy)
        self.btn_play_mode.setMinimumSize(QtCore.QSize(18, 18))
        self.btn_play_mode.setMaximumSize(QtCore.QSize(18, 18))
        self.btn_play_mode.setText("")
        self.btn_play_mode.setObjectName("btn_play_mode")
        self.horizontalLayout_2.addWidget(self.btn_play_mode)
        spacerItem25 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem25)
        self.btn_desktop_lyric = QtWidgets.QPushButton(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_desktop_lyric.sizePolicy().hasHeightForWidth())
        self.btn_desktop_lyric.setSizePolicy(sizePolicy)
        self.btn_desktop_lyric.setMinimumSize(QtCore.QSize(22, 22))
        self.btn_desktop_lyric.setMaximumSize(QtCore.QSize(22, 22))
        self.btn_desktop_lyric.setText("")
        self.btn_desktop_lyric.setObjectName("btn_desktop_lyric")
        self.horizontalLayout_2.addWidget(self.btn_desktop_lyric)
        spacerItem26 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem26)
        self.btn_play_list = QtWidgets.QPushButton(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play_list.sizePolicy().hasHeightForWidth())
        self.btn_play_list.setSizePolicy(sizePolicy)
        self.btn_play_list.setMinimumSize(QtCore.QSize(14, 14))
        self.btn_play_list.setMaximumSize(QtCore.QSize(14, 14))
        self.btn_play_list.setText("")
        self.btn_play_list.setObjectName("btn_play_list")
        self.horizontalLayout_2.addWidget(self.btn_play_list)
        self.label_play_count = QtWidgets.QLabel(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_play_count.sizePolicy().hasHeightForWidth())
        self.label_play_count.setSizePolicy(sizePolicy)
        self.label_play_count.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_play_count.setText("")
        self.label_play_count.setObjectName("label_play_count")
        self.horizontalLayout_2.addWidget(self.label_play_count)
        self.verticalLayout.addWidget(self.footer)

        self.retranslateUi(Form)
        self.main_stacked_widget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.music_count.setText(_translate("Form", "歌曲数\n"
"7"))
        self.music_list_image.setText(_translate("Form", "TextLabel"))
        self.music_list_play_count.setText(_translate("Form", "播放数\n"
"78"))
        self.music_list_name.setText(_translate("Form", "TextLabel"))
        self.music_list_date.setText(_translate("Form", "2018-12-12创建"))
        self.label_4.setText(_translate("Form", "歌曲列表"))
        self.label.setText(_translate("Form", "本地音乐"))
        self.label_2.setText(_translate("Form", "300首音乐"))
        self.btn_choose_dir.setText(_translate("Form", "选择目录"))
        self.label_title.setText(_translate("Form", "title"))
        self.label_artist.setText(_translate("Form", "artist"))
        self.label_album.setText(_translate("Form", "album"))
        self.label_pos.setText(_translate("Form", "00:00"))
        self.label_duration.setText(_translate("Form", "00:00"))

